Update terraform_snowflake.yml

diff --git a/.github/workflows/terraform_snowflake.yml b/.github/workflows/terraform_snowflake.yml
--- a/.github/workflows/terraform_snowflake.yml
+++ b/.github/workflows/terraform_snowflake.yml
@@ -41,6 +41,13 @@ jobs:
       - name: Plan Terraform
         run: |
           echo "SNOWFLAKE_PRIVATE_KEY=$(echo $SNOWFLAKE_PRIVATE_KEY_B64 | base64 --decode)" >> $GITHUB_ENV
+          if [ -z "$SNOWFLAKE_PRIVATE_KEY" ]; then
+            echo "❌ SNOWFLAKE_PRIVATE_KEY is missing!"
+            exit 1
+          else
+            echo "✅ SNOWFLAKE_PRIVATE_KEY is set!"
+          fi
+          echo "SNOWFLAKE_PRIVATE_KEY=$(echo $SNOWFLAKE_PRIVATE_KEY_B64 | base64 --decode)" >> $GITHUB_ENV
           terraform plan -var="SNOWFLAKE_USER=$SNOWFLAKE_USER" -var="SNOWFLAKE_PRIVATE_KEY=$SNOWFLAKE_PRIVATE_KEY" -var-file=terraform.tfvars
         working-directory: environment
 
